# Generated by Django 3.1.4 on 2020-12-11 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('penguin', '0006_product_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_delete_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_items', models.ManyToManyField(to='penguin.Product')),
            ],
        ),
    ]
