# Generated by Django 3.1.4 on 2020-12-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201209_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
