# Generated by Django 3.1.4 on 2020-12-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penguin', '0006_product_owners'),
        ('users', '0007_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='user_items',
            field=models.ManyToManyField(default=None, to='penguin.Product'),
        ),
    ]
