# Generated by Django 3.1.3 on 2020-11-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penguin', '0002_auto_20201128_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcatagory',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='penguin/images'),
        ),
    ]
