# Generated by Django 3.1.4 on 2020-12-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penguin', '0006_product_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owners',
        ),
    ]
